// AI-generated illustrative product photos. Cell order is stable and keyed by seed ID,
// with a name fallback for historical cart/order snapshots. See assets/products/PROMPTS.md.
const atlases = {
  'rice': new URL('../assets/products/rice.jpg', import.meta.url).href,
  'pulses': new URL('../assets/products/pulses.jpg', import.meta.url).href,
  'vegetables': new URL('../assets/products/vegetables.jpg', import.meta.url).href,
  'fruits': new URL('../assets/products/fruits.jpg', import.meta.url).href,
  'dairy': new URL('../assets/products/dairy.jpg', import.meta.url).href,
  'bakery': new URL('../assets/products/bakery.jpg', import.meta.url).href,
  'oils': new URL('../assets/products/oils.jpg', import.meta.url).href,
  'spices': new URL('../assets/products/spices.jpg', import.meta.url).href,
  'breakfast': new URL('../assets/products/breakfast.jpg', import.meta.url).href,
  'dry-fruits': new URL('../assets/products/dry-fruits.jpg', import.meta.url).href,
  'snacks': new URL('../assets/products/snacks.jpg', import.meta.url).href,
  'beverages': new URL('../assets/products/beverages.jpg', import.meta.url).href,
  'frozen-foods': new URL('../assets/products/frozen-foods.jpg', import.meta.url).href,
  'personal-care': new URL('../assets/products/personal-care.jpg', import.meta.url).href,
  'household': new URL('../assets/products/household.jpg', import.meta.url).href,
  'pet-care': new URL('../assets/products/pet-care.jpg', import.meta.url).href,
};

export const productArtworkEntries = [
  { id: "s-rice-1", name: "Premium Basmati Rice", atlas: 'rice', index: 0 },
  { id: "s-rice-2", name: "Organic Brown Rice", atlas: 'rice', index: 1 },
  { id: "s-rice-3", name: "Jasmine Fragrant Rice", atlas: 'rice', index: 2 },
  { id: "s-rice-4", name: "Sona Masoori Rice", atlas: 'rice', index: 3 },
  { id: "s-rice-5", name: "Organic Quinoa", atlas: 'rice', index: 4 },
  { id: "s-rice-6", name: "Black Forbidden Rice", atlas: 'rice', index: 5 },
  { id: "s-rice-7", name: "Arborio Risotto Rice", atlas: 'rice', index: 6 },
  { id: "s-rice-8", name: "Red Matta Rice", atlas: 'rice', index: 7 },
  { id: "s-rice-9", name: "Wild Rice Mix", atlas: 'rice', index: 8 },
  { id: "s-rice-10", name: "Poha (Flattened Rice)", atlas: 'rice', index: 9 },
  { id: "s-rice-11", name: "Idli Rice", atlas: 'rice', index: 10 },
  { id: "s-rice-12", name: "Bulgur Wheat", atlas: 'rice', index: 11 },
  { id: "s-rice-13", name: "Couscous", atlas: 'rice', index: 12 },
  { id: "s-rice-14", name: "Pearl Millet (Bajra)", atlas: 'rice', index: 13 },
  { id: "s-rice-15", name: "Finger Millet (Ragi)", atlas: 'rice', index: 14 },
  { id: "s-pul-1", name: "Yellow Moong Dal", atlas: 'pulses', index: 0 },
  { id: "s-pul-2", name: "Red Masoor Dal", atlas: 'pulses', index: 1 },
  { id: "s-pul-3", name: "Chana Dal", atlas: 'pulses', index: 2 },
  { id: "s-pul-4", name: "Urad Dal White", atlas: 'pulses', index: 3 },
  { id: "s-pul-5", name: "Toor Dal Premium", atlas: 'pulses', index: 4 },
  { id: "s-pul-6", name: "Black Urad Dal Whole", atlas: 'pulses', index: 5 },
  { id: "s-pul-7", name: "Kabuli Chana (Chickpeas)", atlas: 'pulses', index: 6 },
  { id: "s-pul-8", name: "Rajma Chitra", atlas: 'pulses', index: 7 },
  { id: "s-pul-9", name: "Green Moong Whole", atlas: 'pulses', index: 8 },
  { id: "s-pul-10", name: "Black Eyed Beans (Lobia)", atlas: 'pulses', index: 9 },
  { id: "s-pul-11", name: "Soyabean Chunks", atlas: 'pulses', index: 10 },
  { id: "s-pul-12", name: "Moth Beans", atlas: 'pulses', index: 11 },
  { id: "s-pul-13", name: "Horse Gram (Kulthi)", atlas: 'pulses', index: 12 },
  { id: "s-pul-14", name: "Green Peas Dry", atlas: 'pulses', index: 13 },
  { id: "s-pul-15", name: "Val Dal (Field Beans)", atlas: 'pulses', index: 14 },
  { id: "s-veg-1", name: "Fresh Roma Tomatoes", atlas: 'vegetables', index: 0 },
  { id: "s-veg-2", name: "Organic Red Onions", atlas: 'vegetables', index: 1 },
  { id: "s-veg-3", name: "Fresh Baby Spinach", atlas: 'vegetables', index: 2 },
  { id: "s-veg-4", name: "English Cucumber", atlas: 'vegetables', index: 3 },
  { id: "s-veg-5", name: "Bell Pepper Trio", atlas: 'vegetables', index: 4 },
  { id: "s-veg-6", name: "Broccoli Florets", atlas: 'vegetables', index: 5 },
  { id: "s-veg-7", name: "Sweet Corn Cobs", atlas: 'vegetables', index: 6 },
  { id: "s-veg-8", name: "Purple Eggplant", atlas: 'vegetables', index: 7 },
  { id: "s-veg-9", name: "Ginger Root", atlas: 'vegetables', index: 8 },
  { id: "s-veg-10", name: "Green Chilies", atlas: 'vegetables', index: 9 },
  { id: "s-veg-11", name: "Cauliflower", atlas: 'vegetables', index: 10 },
  { id: "s-veg-12", name: "Carrots Orange", atlas: 'vegetables', index: 11 },
  { id: "s-veg-13", name: "Potato (New Crop)", atlas: 'vegetables', index: 12 },
  { id: "s-veg-14", name: "Garlic Bulbs", atlas: 'vegetables', index: 13 },
  { id: "s-veg-15", name: "Mushrooms Button", atlas: 'vegetables', index: 14 },
  { id: "s-fru-1", name: "Royal Gala Apples", atlas: 'fruits', index: 0 },
  { id: "s-fru-2", name: "Fresh Cavendish Bananas", atlas: 'fruits', index: 1 },
  { id: "s-fru-3", name: "Alphonso Mangoes", atlas: 'fruits', index: 2 },
  { id: "s-fru-4", name: "Hass Avocados", atlas: 'fruits', index: 3 },
  { id: "s-fru-5", name: "Green Seedless Grapes", atlas: 'fruits', index: 4 },
  { id: "s-fru-6", name: "Pomegranate Premium", atlas: 'fruits', index: 5 },
  { id: "s-fru-7", name: "Fresh Oranges", atlas: 'fruits', index: 6 },
  { id: "s-fru-8", name: "Kiwi Fruit", atlas: 'fruits', index: 7 },
  { id: "s-fru-9", name: "Red Cherries", atlas: 'fruits', index: 8 },
  { id: "s-fru-10", name: "Blueberries", atlas: 'fruits', index: 9 },
  { id: "s-fru-11", name: "Watermelon Whole", atlas: 'fruits', index: 10 },
  { id: "s-fru-12", name: "Papaya Semi-Ripe", atlas: 'fruits', index: 11 },
  { id: "s-fru-13", name: "Pineapple Queen", atlas: 'fruits', index: 12 },
  { id: "s-fru-14", name: "Plums Red", atlas: 'fruits', index: 13 },
  { id: "s-fru-15", name: "Pears Nashpati", atlas: 'fruits', index: 14 },
  { id: "s-dai-1", name: "Full Cream Fresh Milk", atlas: 'dairy', index: 0 },
  { id: "s-dai-2", name: "Greek Plain Yogurt", atlas: 'dairy', index: 1 },
  { id: "s-dai-3", name: "Salted Farm Butter", atlas: 'dairy', index: 2 },
  { id: "s-dai-4", name: "Paneer (Cottage Cheese)", atlas: 'dairy', index: 3 },
  { id: "s-dai-5", name: "Cheddar Cheese Slices", atlas: 'dairy', index: 4 },
  { id: "s-dai-6", name: "Fresh Mozzarella", atlas: 'dairy', index: 5 },
  { id: "s-dai-7", name: "Low Fat Skimmed Milk", atlas: 'dairy', index: 6 },
  { id: "s-dai-8", name: "Strawberry Milkshake", atlas: 'dairy', index: 7 },
  { id: "s-dai-9", name: "Condensed Milk", atlas: 'dairy', index: 8 },
  { id: "s-dai-10", name: "Fresh Whipping Cream", atlas: 'dairy', index: 9 },
  { id: "s-dai-11", name: "Probiotic Curd", atlas: 'dairy', index: 10 },
  { id: "s-dai-12", name: "Clarified Butter (Ghee)", atlas: 'dairy', index: 11 },
  { id: "s-dai-13", name: "Blue Cheese", atlas: 'dairy', index: 12 },
  { id: "s-dai-14", name: "Oat Milk (Dairy Free)", atlas: 'dairy', index: 13 },
  { id: "s-dai-15", name: "Flavored Greek Yogurt", atlas: 'dairy', index: 14 },
  { id: "s-bak-1", name: "Whole Wheat Sourdough", atlas: 'bakery', index: 0 },
  { id: "s-bak-2", name: "Chocolate Chip Cookies", atlas: 'bakery', index: 1 },
  { id: "s-bak-3", name: "Butter Croissants", atlas: 'bakery', index: 2 },
  { id: "s-bak-4", name: "Multigrain Brown Bread", atlas: 'bakery', index: 3 },
  { id: "s-bak-5", name: "Blueberry Muffins", atlas: 'bakery', index: 4 },
  { id: "s-bak-6", name: "Garlic Breadsticks", atlas: 'bakery', index: 5 },
  { id: "s-bak-7", name: "Red Velvet Cake", atlas: 'bakery', index: 6 },
  { id: "s-bak-8", name: "Pita Bread Whole Wheat", atlas: 'bakery', index: 7 },
  { id: "s-bak-9", name: "Oatmeal Raisin Cookies", atlas: 'bakery', index: 8 },
  { id: "s-bak-10", name: "Bagel Plain", atlas: 'bakery', index: 9 },
  { id: "s-bak-11", name: "Apple Pie Slice", atlas: 'bakery', index: 10 },
  { id: "s-bak-12", name: "Burger Buns Sesame", atlas: 'bakery', index: 11 },
  { id: "s-bak-13", name: "Dinner Rolls", atlas: 'bakery', index: 12 },
  { id: "s-bak-14", name: "Fruit Cake Bar", atlas: 'bakery', index: 13 },
  { id: "s-bak-15", name: "Chocolate Donuts", atlas: 'bakery', index: 14 },
  { id: "s-oil-1", name: "Extra Virgin Olive Oil", atlas: 'oils', index: 0 },
  { id: "s-oil-2", name: "Cold Pressed Mustard Oil", atlas: 'oils', index: 1 },
  { id: "s-oil-3", name: "Sunflower Refined Oil", atlas: 'oils', index: 2 },
  { id: "s-oil-4", name: "Groundnut Cold Pressed Oil", atlas: 'oils', index: 3 },
  { id: "s-oil-5", name: "Rice Bran Oil", atlas: 'oils', index: 4 },
  { id: "s-oil-6", name: "Coconut Cooking Oil", atlas: 'oils', index: 5 },
  { id: "s-oil-7", name: "Sesame Oil (Gingelly)", atlas: 'oils', index: 6 },
  { id: "s-oil-8", name: "Avocado Oil", atlas: 'oils', index: 7 },
  { id: "s-oil-9", name: "Canola Oil", atlas: 'oils', index: 8 },
  { id: "s-oil-10", name: "Castor Oil Pure", atlas: 'oils', index: 9 },
  { id: "s-oil-11", name: "Grapeseed Oil", atlas: 'oils', index: 10 },
  { id: "s-oil-12", name: "Flaxseed Oil", atlas: 'oils', index: 11 },
  { id: "s-oil-13", name: "Soybean Refined Oil", atlas: 'oils', index: 12 },
  { id: "s-oil-14", name: "Corn Oil Premium", atlas: 'oils', index: 13 },
  { id: "s-oil-15", name: "Walnut Oil", atlas: 'oils', index: 14 },
  { id: "s-spi-1", name: "Organic Turmeric Powder", atlas: 'spices', index: 0 },
  { id: "s-spi-2", name: "Whole Black Peppercorns", atlas: 'spices', index: 1 },
  { id: "s-spi-3", name: "Red Chili Powder (Lal Mirch)", atlas: 'spices', index: 2 },
  { id: "s-spi-4", name: "Cumin Seeds (Jeera)", atlas: 'spices', index: 3 },
  { id: "s-spi-5", name: "Coriander Powder (Dhania)", atlas: 'spices', index: 4 },
  { id: "s-spi-6", name: "Green Cardamom (Elaichi)", atlas: 'spices', index: 5 },
  { id: "s-spi-7", name: "Cloves (Laung)", atlas: 'spices', index: 6 },
  { id: "s-spi-8", name: "Cinnamon Sticks", atlas: 'spices', index: 7 },
  { id: "s-spi-9", name: "Garam Masala", atlas: 'spices', index: 8 },
  { id: "s-spi-10", name: "Saffron (Kesar)", atlas: 'spices', index: 9 },
  { id: "s-spi-11", name: "Star Anise", atlas: 'spices', index: 10 },
  { id: "s-spi-12", name: "Bay Leaves (Tejpatta)", atlas: 'spices', index: 11 },
  { id: "s-spi-13", name: "Nutmeg Whole", atlas: 'spices', index: 12 },
  { id: "s-spi-14", name: "Black Salt Powder", atlas: 'spices', index: 13 },
  { id: "s-spi-15", name: "Fenugreek Seeds (Methi)", atlas: 'spices', index: 14 },
  { id: "s-bre-1", name: "Rolled Oats", atlas: 'breakfast', index: 0 },
  { id: "s-bre-2", name: "Honey Nut Muesli", atlas: 'breakfast', index: 1 },
  { id: "s-bre-3", name: "Corn Flakes Original", atlas: 'breakfast', index: 2 },
  { id: "s-bre-4", name: "Chocos Cereal", atlas: 'breakfast', index: 3 },
  { id: "s-bre-5", name: "Peanut Butter Creamy", atlas: 'breakfast', index: 4 },
  { id: "s-bre-6", name: "Fruit Jam Mixed", atlas: 'breakfast', index: 5 },
  { id: "s-bre-7", name: "Instant Upma Mix", atlas: 'breakfast', index: 6 },
  { id: "s-bre-8", name: "Honey Pure Natural", atlas: 'breakfast', index: 7 },
  { id: "s-bre-9", name: "Granola Bars Assorted", atlas: 'breakfast', index: 8 },
  { id: "s-bre-10", name: "Vermicelli Roasted", atlas: 'breakfast', index: 9 },
  { id: "s-bre-11", name: "Maple Syrup", atlas: 'breakfast', index: 10 },
  { id: "s-bre-12", name: "Pancake Mix", atlas: 'breakfast', index: 11 },
  { id: "s-bre-13", name: "Chia Seeds Organic", atlas: 'breakfast', index: 12 },
  { id: "s-bre-14", name: "Chocolate Hazelnut Spread", atlas: 'breakfast', index: 13 },
  { id: "s-bre-15", name: "Idli Podi (Gunpowder)", atlas: 'breakfast', index: 14 },
  { id: "s-dry-1", name: "California Almonds", atlas: 'dry-fruits', index: 0 },
  { id: "s-dry-2", name: "Whole Cashew Nuts", atlas: 'dry-fruits', index: 1 },
  { id: "s-dry-3", name: "Shelled Walnuts", atlas: 'dry-fruits', index: 2 },
  { id: "s-dry-4", name: "Pistachios Roasted", atlas: 'dry-fruits', index: 3 },
  { id: "s-dry-5", name: "Dried Raisins (Kishmish)", atlas: 'dry-fruits', index: 4 },
  { id: "s-dry-6", name: "Dried Dates (Khajoor)", atlas: 'dry-fruits', index: 5 },
  { id: "s-dry-7", name: "Anjeer (Dried Figs)", atlas: 'dry-fruits', index: 6 },
  { id: "s-dry-8", name: "Apricots Dried", atlas: 'dry-fruits', index: 7 },
  { id: "s-dry-9", name: "Dried Cranberries", atlas: 'dry-fruits', index: 8 },
  { id: "s-dry-10", name: "Pecan Nuts", atlas: 'dry-fruits', index: 9 },
  { id: "s-dry-11", name: "Brazil Nuts", atlas: 'dry-fruits', index: 10 },
  { id: "s-dry-12", name: "Hazelnut Shelled", atlas: 'dry-fruits', index: 11 },
  { id: "s-dry-13", name: "Pine Nuts (Chilgoza)", atlas: 'dry-fruits', index: 12 },
  { id: "s-dry-14", name: "Prunes Pitted", atlas: 'dry-fruits', index: 13 },
  { id: "s-dry-15", name: "Makhana (Fox Nuts)", atlas: 'dry-fruits', index: 14 },
  { id: "s-sna-1", name: "Classic Potato Chips", atlas: 'snacks', index: 0 },
  { id: "s-sna-2", name: "Digestive Biscuits", atlas: 'snacks', index: 1 },
  { id: "s-sna-3", name: "Milk Chocolate Bar", atlas: 'snacks', index: 2 },
  { id: "s-sna-4", name: "Roasted Peanuts", atlas: 'snacks', index: 3 },
  { id: "s-sna-5", name: "Instant Noodles", atlas: 'snacks', index: 4 },
  { id: "s-sna-6", name: "Popcorn Kernels", atlas: 'snacks', index: 5 },
  { id: "s-sna-7", name: "Tortilla Chips", atlas: 'snacks', index: 6 },
  { id: "s-sna-8", name: "Pretzels Salted", atlas: 'snacks', index: 7 },
  { id: "s-sna-9", name: "Dark Chocolate 70%", atlas: 'snacks', index: 8 },
  { id: "s-sna-10", name: "Gummy Bears", atlas: 'snacks', index: 9 },
  { id: "s-sna-11", name: "Rice Crackers", atlas: 'snacks', index: 10 },
  { id: "s-sna-12", name: "Corn Puffs", atlas: 'snacks', index: 11 },
  { id: "s-sna-13", name: "Wafer Biscuits", atlas: 'snacks', index: 12 },
  { id: "s-sna-14", name: "Pistachio Biscuits", atlas: 'snacks', index: 13 },
  { id: "s-sna-15", name: "Fruit & Nut Bar", atlas: 'snacks', index: 14 },
  { id: "s-bev-1", name: "Pure Orange Juice", atlas: 'beverages', index: 0 },
  { id: "s-bev-2", name: "Assam Strong Tea", atlas: 'beverages', index: 1 },
  { id: "s-bev-3", name: "Instant Coffee Powder", atlas: 'beverages', index: 2 },
  { id: "s-bev-4", name: "Sparkling Water", atlas: 'beverages', index: 3 },
  { id: "s-bev-5", name: "Cola Soft Drink", atlas: 'beverages', index: 4 },
  { id: "s-bev-6", name: "Coconut Water", atlas: 'beverages', index: 5 },
  { id: "s-bev-7", name: "Green Tea Bags", atlas: 'beverages', index: 6 },
  { id: "s-bev-8", name: "Apple Juice Tetra", atlas: 'beverages', index: 7 },
  { id: "s-bev-9", name: "Energy Drink", atlas: 'beverages', index: 8 },
  { id: "s-bev-10", name: "Tomato Juice", atlas: 'beverages', index: 9 },
  { id: "s-bev-11", name: "Lemonade Can", atlas: 'beverages', index: 10 },
  { id: "s-bev-12", name: "Iced Coffee Latte", atlas: 'beverages', index: 11 },
  { id: "s-bev-13", name: "Aloe Vera Juice", atlas: 'beverages', index: 12 },
  { id: "s-bev-14", name: "Chamomile Tea", atlas: 'beverages', index: 13 },
  { id: "s-bev-15", name: "Drinking Water", atlas: 'beverages', index: 14 },
  { id: "s-fro-1", name: "Frozen Garden Peas", atlas: 'frozen-foods', index: 0 },
  { id: "s-fro-2", name: "Veggie Margherita Pizza", atlas: 'frozen-foods', index: 1 },
  { id: "s-fro-3", name: "French Fries Classic", atlas: 'frozen-foods', index: 2 },
  { id: "s-fro-4", name: "Frozen Sweet Corn", atlas: 'frozen-foods', index: 3 },
  { id: "s-fro-5", name: "Chicken Nuggets", atlas: 'frozen-foods', index: 4 },
  { id: "s-fro-6", name: "Vegetable Spring Rolls", atlas: 'frozen-foods', index: 5 },
  { id: "s-fro-7", name: "Frozen Blueberries", atlas: 'frozen-foods', index: 6 },
  { id: "s-fro-8", name: "Paneer Tikka Frozen", atlas: 'frozen-foods', index: 7 },
  { id: "s-fro-9", name: "Frozen Mixed Veg", atlas: 'frozen-foods', index: 8 },
  { id: "s-fro-10", name: "Chicken Tikka Pizza", atlas: 'frozen-foods', index: 9 },
  { id: "s-fro-11", name: "Frozen Prawns", atlas: 'frozen-foods', index: 10 },
  { id: "s-fro-12", name: "Potato Wedges", atlas: 'frozen-foods', index: 11 },
  { id: "s-fro-13", name: "Ice Cream Vanilla", atlas: 'frozen-foods', index: 12 },
  { id: "s-fro-14", name: "Falafel Mix Frozen", atlas: 'frozen-foods', index: 13 },
  { id: "s-fro-15", name: "Frozen Strawberries", atlas: 'frozen-foods', index: 14 },
  { id: "s-per-1", name: "Herbal Aloe Shampoo", atlas: 'personal-care', index: 0 },
  { id: "s-per-2", name: "Charcoal Face Wash", atlas: 'personal-care', index: 1 },
  { id: "s-per-3", name: "Moisturizing Lotion", atlas: 'personal-care', index: 2 },
  { id: "s-per-4", name: "Antiseptic Liquid", atlas: 'personal-care', index: 3 },
  { id: "s-per-5", name: "Toothpaste Mint", atlas: 'personal-care', index: 4 },
  { id: "s-per-6", name: "Bath Soap Rose", atlas: 'personal-care', index: 5 },
  { id: "s-per-7", name: "Deodorant Spray", atlas: 'personal-care', index: 6 },
  { id: "s-per-8", name: "Sunscreen SPF 50", atlas: 'personal-care', index: 7 },
  { id: "s-per-9", name: "Hand Wash Refill", atlas: 'personal-care', index: 8 },
  { id: "s-per-10", name: "Shaving Foam", atlas: 'personal-care', index: 9 },
  { id: "s-per-11", name: "Mouthwash Cool Mint", atlas: 'personal-care', index: 10 },
  { id: "s-per-12", name: "Hair Oil Coconut", atlas: 'personal-care', index: 11 },
  { id: "s-per-13", name: "Body Wash Gel", atlas: 'personal-care', index: 12 },
  { id: "s-per-14", name: "Face Mask Sheet", atlas: 'personal-care', index: 13 },
  { id: "s-per-15", name: "Hand Sanitizer", atlas: 'personal-care', index: 14 },
  { id: "s-hou-1", name: "Liquid Laundry Detergent", atlas: 'household', index: 0 },
  { id: "s-hou-2", name: "Multi-Surface Cleaner", atlas: 'household', index: 1 },
  { id: "s-hou-3", name: "Dishwash Liquid", atlas: 'household', index: 2 },
  { id: "s-hou-4", name: "Kitchen Paper Towels", atlas: 'household', index: 3 },
  { id: "s-hou-5", name: "Toilet Cleaner Blue", atlas: 'household', index: 4 },
  { id: "s-hou-6", name: "Floor Mop Set", atlas: 'household', index: 5 },
  { id: "s-hou-7", name: "Garbage Bags Large", atlas: 'household', index: 6 },
  { id: "s-hou-8", name: "Aluminum Foil Roll", atlas: 'household', index: 7 },
  { id: "s-hou-9", name: "Air Freshener Spray", atlas: 'household', index: 8 },
  { id: "s-hou-10", name: "Sponge Scrubber", atlas: 'household', index: 9 },
  { id: "s-hou-11", name: "Fabric Conditioner", atlas: 'household', index: 10 },
  { id: "s-hou-12", name: "Glass Cleaner", atlas: 'household', index: 11 },
  { id: "s-hou-13", name: "Shoe Polish Black", atlas: 'household', index: 12 },
  { id: "s-hou-14", name: "Mosquito Repellent", atlas: 'household', index: 13 },
  { id: "s-hou-15", name: "Matches Box", atlas: 'household', index: 14 },
  { id: "s-pet-1", name: "Adult Dog Food - Chicken", atlas: 'pet-care', index: 0 },
  { id: "s-pet-2", name: "Crunchy Cat Treats", atlas: 'pet-care', index: 1 },
  { id: "s-pet-3", name: "Puppy Dry Food", atlas: 'pet-care', index: 2 },
  { id: "s-pet-4", name: "Cat Litter Fragrant", atlas: 'pet-care', index: 3 },
  { id: "s-pet-5", name: "Dog Chew Bones", atlas: 'pet-care', index: 4 },
  { id: "s-pet-6", name: "Bird Seed Mix", atlas: 'pet-care', index: 5 },
  { id: "s-pet-7", name: "Pet Shampoo Gentle", atlas: 'pet-care', index: 6 },
  { id: "s-pet-8", name: "Kitten Wet Food", atlas: 'pet-care', index: 7 },
  { id: "s-pet-9", name: "Dog Leash Durable", atlas: 'pet-care', index: 8 },
  { id: "s-pet-10", name: "Fish Flake Food", atlas: 'pet-care', index: 9 },
  { id: "s-pet-11", name: "Pet De-shedding Tool", atlas: 'pet-care', index: 10 },
  { id: "s-pet-12", name: "Guinea Pig Pellets", atlas: 'pet-care', index: 11 },
  { id: "s-pet-13", name: "Pet Odor Remover", atlas: 'pet-care', index: 12 },
  { id: "s-pet-14", name: "Dog Squeaky Toy", atlas: 'pet-care', index: 13 },
  { id: "s-pet-15", name: "Catnip Spray", atlas: 'pet-care', index: 14 },
];

const byId = new Map(productArtworkEntries.map(entry => [entry.id, entry]));
const byName = new Map(productArtworkEntries.map(entry => [entry.name.toLowerCase(), entry]));

export function getProductArtwork(product = {}) {
  const entry = byId.get(product.externalId) || byName.get(String(product.name || '').toLowerCase());
  return entry ? { src: atlases[entry.atlas], column: entry.index % 4, row: Math.floor(entry.index / 4) } : null;
}

